### ISSUE TITLE
Build errors when using latest Ember and ember-cli-chart

### ISSUE THREAD

**Issue by jdelliot** [aomran/ember-cli-chart#76]
I am seeing the following build error when I use this add-on.

```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open 'C:\repos\ember-quickstart\tmp\source_map_concat-input_base_path-ECsfiHVC.tmp\C:\repos\ember-quickstart\node_modules\chart.js\dist\Chart.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at SourceMap.addFile (C:\repos\ember-quickstart\node_modules\fast-sourcemap-concat\lib\source-map.js:75:31)
    at C:\repos\ember-quickstart\node_modules\broccoli-concat\concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (C:\repos\ember-quickstart\node_modules\broccoli-concat\concat.js:198:24)
    at C:\repos\ember-quickstart\node_modules\fast-sourcemap-concat\lib\source-map.js:393:12
    at initializePromise (C:\repos\ember-quickstart\node_modules\rsvp\dist\rsvp.js:567:5)
    at new Promise (C:\repos\ember-quickstart\node_modules\rsvp\dist\rsvp.js:1039:33)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (C:\repos\ember-quickstart\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (C:\repos\ember-quickstart\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (C:\repos\ember-quickstart\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:10:53)
    at mergeTrees (C:\repos\ember-quickstart\node_modules\ember-cli\lib\broccoli\merge-trees.js:85:33)
    at EmberApp._mergeTrees (C:\repos\ember-quickstart\node_modules\ember-cli\lib\broccoli\ember-app.js:1817:12)
    at EmberApp.javascript (C:\repos\ember-quickstart\node_modules\ember-cli\lib\broccoli\ember-app.js:1299:17)
    at EmberApp.toArray (C:\repos\ember-quickstart\node_modules\ember-cli\lib\broccoli\ember-app.js:1674:12)
    at EmberApp.toTree (C:\repos\ember-quickstart\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:38)
    at module.exports (C:\repos\ember-quickstart\ember-cli-build.js:22:14)
    at Builder.setupBroccoliBuilder (C:\repos\ember-quickstart\node_modules\ember-cli\lib\models\builder.js:56:19)
```

To verify my configuration I rolled back to the simple ember-quickstart app. Still repros. Any ideas what is going on here?

Thanks in advance.

**Comment by Techn1x** [comment]
Does ember-cli-chart 3.2.0 work for you? Could be related to my issue..
https://github.com/aomran/ember-cli-chart/issues/77

**Comment by aomran** [comment]
I installed `ember-cli@2.13` and generated a fresh app. I installed this addon and it worked. This is all using node `v6.11.0`.

What node version are you using and does `npm install` work for you?

**Comment by jdelliot** [comment]
I am using:
```
ember-cli: 2.13.3
node: 6.11.0
os: win32 x64
```
Contents of my package.json:
```
{
  "name": "ember-quickstart",
  "version": "0.0.0",
  "description": "Small description for ember-quickstart goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.3",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.3.0",
    "ember-cli-chart": "^3.3.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.13.2",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.13.3",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  },
  "private": true
}
```
I tried creating a new ember project (ember new testApp), then installed ember-cli-chart (ember install ember-cli-chart), and then build (ember build). Same error. I ran npm install (npm install ember-cli-chart) and then re-ran the ember install and build. Same error.

What else can I offer to help diagnose. I have zipped up my test project and attached it.

[testApp.zip](https://github.com/aomran/ember-cli-chart/files/1126765/testApp.zip)

Let me know what you think.

Thanks in advance, John

**Comment by jdelliot** [comment]
OK. A bit more information. If I run only npm install ember-cli-chart, then ember build still works. If I run ember install ember-cli-chart I get the the error above.

Thanks again, John

**Comment by escobera** [comment]
This error seems to only occur on windows.

**Comment by aomran** [comment]
likely duplicates #77 so closing this -- let's keep the conversation there.
