### ISSUE TITLE
must use Ember.set() to set the `datasets` property

### ISSUE THREAD

**Issue by sibijohn72** [aomran/ember-cli-chart#88]
Hey, i am getting the following error when trying to use this addon.

ember.debug.js:26518 Assertion Failed: You must use Ember.set() to set the `datasets` property (of [object Object]) to `[object Object]`.
Error
    at Object.assert (http://localhost:4200/assets/vendor.js:24286:15)
    at Object.SETTER_FUNCTION [as datasets] (http://localhost:4200/assets/vendor.js:34120:38)
    at initConfig (http://localhost:4200/assets/vendor.js:69170:17)
    at Chart.construct (http://localhost:4200/assets/vendor.js:69212:13)
    at new Chart (http://localhost:4200/assets/vendor.js:71759:8)
    at Class.didInsertElement (http://localhost:4200/assets/vendor.js:80192:19)
    at Class.superWrapper [as didInsertElement] (http://localhost:4200/assets/vendor.js:55970:22)
    at Class.trigger (http://localhost:4200/assets/vendor.js:58003:23)
    at Class.superWrapper [as trigger] (http://localhost:4200/assets/vendor.js:55970:22)
    at CurlyComponentManager.didCreate (http://localhost:4200/assets/vendor.js:30094:19)

**Comment by sibijohn72** [comment]
My application is running on the following versions of Ember and jQuery.
Ember  : 2.14.0
jQuery : 3.2.1

**Comment by RobbieTheWagner** [comment]
I'm guessing this is fixed now?
